/* Autogenerated by script/mkversion.sh */
#define SAMBA_VERSION_MAJOR 
#define SAMBA_VERSION_MINOR 
#define SAMBA_VERSION_RELEASE 
#define SAMBA_VERSION_OFFICIAL_STRING ".."
#define SAMBA_VERSION_STRING ".."
